---
- name: 'get vbox master node uuid'
  shell:
    cmd: /usr/sbin/fence_vbox -o list -l root -x -a {{ fencevbox.dom0 }} -p {{ fencevbox.dom0_passwd }} | /usr/bin/grep pacemaker_node1 | /usr/bin/cut -d ',' -f 2
  register: master_uuid

- name: 'get vbox slave node uuid'
  shell:
    cmd: /usr/sbin/fence_vbox -o list -l root -x -a {{ fencevbox.dom0 }} -p {{ fencevbox.dom0_passwd }} | /usr/bin/grep pacemaker_node2 | /usr/bin/cut -d ',' -f 2
  register: slave_uuid

- name: 'create STONITH agent logfile'
  file:
    path: /var/log/stonith.log
    state: touch

- name: 'add stonith vbox'
  shell:
    cmd: >
      /usr/sbin/pcs stonith create stonith-vbox-master fence_vbox
      username="{{ fencevbox.dom0_user }}"
      password="{{ fencevbox.dom0_passwd }}"
      ssh=yes
      use_sudo=true
      ip="{{ fencevbox.dom0 }}"
      plug="{{ master_uuid.stdout }}"
      pcmk_host_map="{{ hostvars['master']['ansible_host'] }}:{{ master_uuid.stdout }}"
      debug_file="/var/log/stonith.log"
      &&
      /usr/sbin/pcs stonith create stonith-vbox-slave fence_vbox
      username="{{ fencevbox.dom0_user }}"
      password="{{ fencevbox.dom0_passwd }}"
      ssh=yes
      use_sudo=true
      ip="{{ fencevbox.dom0 }}"
      plug="{{ slave_uuid.stdout }}"
      pcmk_host_map="{{ hostvars['slave']['ansible_host'] }}:{{ slave_uuid.stdout }}"
      debug_file="/var/log/stonith.log"
  register: stonith_failure
  failed_when: "stonith_failure.rc != 0 and stonith_failure.rc == 1 and stonith_failure.stderr != 'Error: \\'stonith-vbox-master\\' already exists'"

- name: 'check stonith resources'
  shell:
    cmd: /usr/sbin/pcs resource cleanup && /usr/sbin/pcs status
  register: stonith_resource

- name: 'show resources'
  debug:
    var: stonith_resource.stdout_lines

- name: 'add location: stonith master on slave node'
  shell:
    cmd: "/usr/sbin/pcs constraint location stonith-vbox-master avoids {{ hostvars['master']['ansible_host'] }}"

- name: 'add location: stonith slave on master node'
  shell:
    cmd: "/usr/sbin/pcs constraint location stonith-vbox-slave avoids {{ hostvars['slave']['ansible_host'] }}"

- name: 'get location constraints'
  shell:
    cmd: "/usr/sbin/pcs resource cleanup && /usr/sbin/pcs constraint location --full"
  register: location_constraints

- name: 'show location constraints'
  debug:
    var: location_constraints.stdout_lines

- name: 'verify everything is ok'
  shell:
    cmd: /usr/sbin/crm_verify -LV

- name: 'enable stonith master and slave'
  shell:
    cmd: /usr/sbin/pcs stonith enable stonith-vbox-master && /usr/sbin/pcs stonith enable stonith-vbox-slave

- name: 'check stonith resources'
  shell:
    cmd: /usr/sbin/pcs stonith cleanup && /usr/sbin/pcs status
  register: stonith_resource

- name: 'show resources'
  debug:
    var: stonith_resource.stdout_lines

- name: 'enable cluster to use STONITH'
  shell:
    cmd: /usr/sbin/pcs property set stonith-enabled=true